version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - dbx_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    #networks:
      #- wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    #networks:
      #- wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    build: .
    ports:
      - '8000:80'
    restart: always
    volumes: 
     - './cms:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
      PHP_EXTENSION_XDEBUG: 1
    #networks:
      #- wpsite
#networks:
  #wpsite:
volumes:
  dbx_data:


# Use this command to start and source the apache ---> source /etc/apache2/envvars && apache2 -D FOREGROUND

